CREATE DATABASE clinica_sorridentes_database;

USE clinica_sorridentes_database;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(32) NOT NULL,
	TIPOUSUARIO VARCHAR(13) NOT NULL
);

INSERT INTO USUARIO(NOME, LOGIN, SENHA, TIPOUSUARIO) VALUES ("Admin","admin","21232f297a57a5a743894a0e4a801fc3","Administrador");

CREATE TABLE PACIENTE(
    IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    SEXO ENUM('Masculino','Feminino') NOT NULL,
    DATANASC DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    PROFISSAO VARCHAR(255) NOT NULL,
    TIPOATENDIMENTO VARCHAR(255) NOT NULL,
    CELULAR VARCHAR(11) NOT NULL,
    ESTADOCIVIL ENUM('Casado(a)','Solteiro(a)','Divorciado(a)','Viúvo(a)','Separado(a)')NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    NUMERO INT(4) NOT NULL,
    SITUACAO ENUM('Atendido','Aguardando Atendimento','Em Espera','Finalizado') DEFAULT 'Em Espera' NOT NULL,
    CIDADE VARCHAR(32) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    COMPLEMENTO VARCHAR(255) NULL,
    CEP VARCHAR(8) NOT NULL
);

CREATE TABLE FICHA_CLINICA(
	IDFICHACLINICA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_FICHA DATETIME,
	OBSERVACOES VARCHAR(255),
	ID_PACIENTE INT
);

ALTER TABLE FICHA_CLINICA ADD CONSTRAINT FK_FICHACLINICA_PACIENTE
FOREIGN KEY FICHA_CLINICA(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

/*Nome foi alterado, necessita modificar as outras chamadas e referências*/
CREATE TABLE PROCEDIMENTO_DENTES(
	IDDENTE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO_DENTE SMALLINT(2),
	PROCEDIMENTO VARCHAR(255),
	IMPORTANCIA ENUM("BAIXA IMPORTANCIA", "MEDIA IMPORTANCIA", "ALTA IMPORTANCIA"),
	VALOR DECIMAL(10,2),
        ORCAMENTO_FINAL DECIMAL(10,2),
        DATA timestamp default current_timestamp(),
        ID_PACIENTE INT
);

ALTER TABLE PROCEDIMENTO_DENTES ADD CONSTRAINT FK_DENTES_PACIENTE
FOREIGN KEY PROCEDIMENTO_DENTES(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

CREATE TABLE MEDICO(
	IDMEDICO INT(11) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	DTANASCIMENTO DATE NOT NULL,
	CONSELHO VARCHAR(255) NOT NULL,
	ESPECIALIDADE VARCHAR(255) NOT NULL,
	FUNCAO VARCHAR(255) NOT NULL,
	TIPODEATENDIMENTO VARCHAR(255) NOT NULL
);