CREATE DATABASE clinica_sorridentes_database;

USE clinica_sorridentes_database;

CREATE TABLE USUARIO(
	IDUSUARIO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	LOGIN VARCHAR(50) NOT NULL UNIQUE,
	SENHA VARCHAR(32) NOT NULL,
	TIPOUSUARIO VARCHAR(13) NOT NULL
);

INSERT INTO USUARIO(NOME, LOGIN, SENHA, TIPOUSUARIO) VALUES ("Admin","admin","21232f297a57a5a743894a0e4a801fc3","Administrador");

CREATE TABLE PACIENTE(
    IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    SEXO VARCHAR(9) NOT NULL,
    DATANASC DATETIME NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    PROFISSAO VARCHAR(255) NOT NULL,
    TIPOATENDIMENTO VARCHAR(255) NOT NULL,
    CELULAR VARCHAR(11) NOT NULL,
    ESTADOCIVIL VARCHAR(11) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    BAIRRO VARCHAR(255) NOT NULL,
    NUMERO INT(2) NOT NULL,
    CIDADE VARCHAR(32) NOT NULL,
    ESTADO CHAR(2) NOT NULL,
    COMPLEMENTO VARCHAR(255) NULL,
    CEP VARCHAR(8) NOT NULL
);

CREATE TABLE FICHA_CLINICA(
	IDFICHACLINICA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_FICHA DATETIME,
	MEDICO_RESPONSAVEL VARCHAR(255) NOT NULL,
	OBSERVACOES VARCHAR(255),
	ID_PACIENTE INT
);

ALTER TABLE FICHA_CLINICA ADD CONSTRAINT FK_FICHACLINICA_PACIENTE
FOREIGN KEY FICHA_CLINICA(ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE);

CREATE TABLE DENTES(
	IDDENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME_DENTE VARCHAR(255),
	PROCEDIMENTO VARCHAR(255),
	VALOR DECIMAL(10,2),
	ID_PACIENTE_DENTE INT,
	ID_FICHACLINICA INT
);

ALTER TABLE DENTES ADD CONSTRAINT FK_DENTES_PACIENTE
FOREIGN KEY DENTES(ID_PACIENTE_DENTE) REFERENCES PACIENTE(IDPACIENTE);

ALTER TABLE DENTES ADD CONSTRAINT FK_DENTES_FICHACLINICA
FOREIGN KEY DENTES(ID_FICHACLINICA) REFERENCES FICHA_CLINICA(IDFICHACLINICA);

CREATE TABLE MEDICO(
	IDMEDICO INT(11) PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	DTANASCIMENTO DATETIME(255) NOT NULL,
	CONSELHO VARCHAR(255) NOT NULL,
	ESPECIALIDADE VARCHAR(255) NOT NULL,
	FUNCAO VARCHAR(255) NOT NULL,
	TIPODEATENDIMENTO VARCHAR(255) NOT NULL
);

/*-----------------------------------------------------------------------------*/
/* /- TESTE -\ */
/*-----------------------------------------------------------------------------*/

INSERT INTO PACIENTE VALUES(NULL, "HUGO SILVA");

INSERT INTO FICHA_CLINICA VALUES
(NULL, '2018-05-17', 'juvencino alves', 'observando', 1);

INSERT INTO DENTES VALUES
(NULL, "CISO EXTERNO", "EXTRAÇÃO", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "PRESA INTERNA", "PIVOT", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "DENTE INTERPROXIMAL", "EXTRAÇÃO", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "PRESA INTERNA", "PIVOT", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "CISO EXTERNO", "EXTRAÇÃO", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "PRESA INTERNA", "PIVOT", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "DENTE INTERPROXIMAL", "EXTRAÇÃO", 5, 1, 1);

INSERT INTO DENTES VALUES
(NULL, "PRESA INTERNA", "PIVOT", 5, 1, 1);

/*-----------------------------------------------------------------------------*/
/* /- QUERYS -\ */
/*-----------------------------------------------------------------------------*/

/* CONSULTA POR NOME E DATA*/

SELECT
P.NOME AS "NOME_PACIENTE",
D.NOME_DENTE,
D.PROCEDIMENTO,
COUNT(D.NOME_DENTE) AS "QUANTIDADE",
SUM(D.VALOR)
FROM DENTES AS D
INNER JOIN PACIENTE AS P
ON P.IDPACIENTE = D.ID_PACIENTE_DENTE
INNER JOIN FICHA_CLINICA AS F
ON D.ID_FICHACLINICA = F.IDFICHACLINICA
WHERE F.DATA_FICHA = '2018-05-17'
AND NOME = "HUGO SILVA"
GROUP BY D.NOME_DENTE;

/*
EX:
+---------------+---------------------+--------------+------------+--------------+
| NOME_PACIENTE | NOME_DENTE          | PROCEDIMENTO | QUANTIDADE | SUM(D.VALOR) |
+---------------+---------------------+--------------+------------+--------------+
| HUGO SILVA    | CISO EXTERNO        | EXTRAÇÃO     |          2 |        10.00 |
| HUGO SILVA    | DENTE INTERPROXIMAL | EXTRAÇÃO     |          2 |        10.00 |
| HUGO SILVA    | PRESA INTERNA       | PIVOT        |          4 |        20.00 |
+---------------+---------------------+--------------+------------+--------------+
*/

/*CONSULTANDO PROCEDIMENTO, QUANTIDADE E PRECO POR DATA*/

SELECT
D.PROCEDIMENTO,
COUNT(D.PROCEDIMENTO) AS QUANTIDADE,
SUM(D.VALOR) AS PRECO
FROM DENTES AS D INNER JOIN FICHA_CLINICA AS F
ON D.ID_FICHACLINICA = F.IDFICHACLINICA
WHERE F.DATA_FICHA = '2018-05-17'
GROUP BY D.PROCEDIMENTO;

/*
EX:
+--------------+------------+-------+
| PROCEDIMENTO | QUANTIDADE | PRECO |
+--------------+------------+-------+
| EXTRAÇÃO     |          4 | 20.00 |
| PIVOT        |          4 | 20.00 |
+--------------+------------+-------+
*/

/*RECEITA DO DIA COM DATA*/

SELECT
SUM(D.VALOR) AS TOTAL_DIA,
F.DATA_FICHA AS DATA
FROM DENTES AS D
INNER JOIN FICHA_CLINICA AS F
ON D.ID_FICHACLINICA = F.IDFICHACLINICA
WHERE F.DATA_FICHA = '2018-05-17';

/*
EX:
+-----------+---------------------+
| TOTAL_DIA | DATA                |
+-----------+---------------------+
|     40.00 | 2018-05-17 00:00:00 |
+-----------+---------------------+
*/